# Generated by Django 2.2.2 on 2019-07-01 23:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Status', models.CharField(choices=[('AVAILABLE', 'Item ready'), ('RESTOCKING', 'Item will be ready in a few days'), ('SOLD', 'Item Sold')], default='SOLD', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Status', models.CharField(choices=[('AVAILABLE', 'Item ready'), ('RESTOCKING', 'Item will be ready in a few days'), ('SOLD', 'Item Sold')], default='SOLD', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Status', models.CharField(choices=[('AVAILABLE', 'Item ready'), ('RESTOCKING', 'Item will be ready in a few days'), ('SOLD', 'Item Sold')], default='SOLD', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Status', models.CharField(choices=[('AVAILABLE', 'Item ready'), ('RESTOCKING', 'Item will be ready in a few days'), ('SOLD', 'Item Sold')], default='SOLD', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
